params:  
  algo:
    name: amp_pfsp

  model:
    name: amp

  network:
    name: amp
    separate: True
    # normalization: layer_norm
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
          scale: 0.02
        sigma_init:
          name: const_initializer
          val: -2.9
        fixed_sigma: True
        learn_sigma: False

    mlp:
      units: [1024, 1024, 512] #[128, 128, 64] # [512, 512, 128] #
      activation: elu # relu
      initializer:
        name: 'orthogonal_initializer'
      regularizer:
        name:  'None'

  config:
    name: zhikong
    env_name: zhikong
    player_pool_type: ''
    player_pool_length: 3
    op_load_path: False
    update_win_rate: 0.8
    games_to_check: 10
    score_to_win: 30
    max_epochs: 10000
    max_update_steps: 5000
    reward_shaper:
        scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 2e-5
    save_win_threshold: 0.005
    grad_norm: 1.5
    entropy_coef: 0.0
    truncate_grads: True
    env_name: zhikong
    e_clip: 0.2
    clip_value: True
    num_actors: 3
    horizon_length: 500
    minibatch_size: 500
    mini_epochs: 6
    critic_coef: 5
    lr_schedule:  linear
    kl_threshold: 0.05
    games_to_track: 10
    normalize_input: False
    normalize_value: False
    seq_length: 5
    save_frequency: 50
    save_best_after: 50

    multi_gpu: False
    mixed_precision: False
    lr_schedule: constant
    print_stats: True
    # truncate_grads: False
    ppo: True
    clip_value: False
    bounds_loss_coef: 10
    amp_obs_demo_buffer_size: 200000
    amp_replay_buffer_size: 200000
    amp_replay_keep_prob: 0.01
    amp_batch_size: 512
    amp_minibatch_size: 4096
    disc_coef: 5
    disc_logit_reg: 0.01
    disc_grad_penalty: 5
    disc_reward_scale: 2
    disc_weight_decay: 0.0001
    normalize_amp_input: True
    enable_eps_greedy: False
    # important
    task_reward_w: 0.0
    disc_reward_w: 1.0

    env_config:
      name: zhikong
      ip: '127.0.1.1'
      worker_index: 888
      config_path: 'rl_games/configs/ma/ppo_zhikong_sp.yaml'
      excute_path: '/home/lzy/lzy/human-ai/Air/9-17/Linux/IL2CPP/Linux/ZK.x86_64' #'/home/lzy/lzy/human-ai/Air/9-17/Linux/IL2CPP/Linux/ZK.x86_64'
      playmode: 1
      num_agents: 2
      red_agents_num: 1
      blue_agents_num: 1
      action_space_type: MultiDiscrete
      ctrl_mode: 0
      apply_agent_ids: True
      central_value: False
      episode_max_length: 500
      change_target: False
      render: False
      record_game_state: False
      dense_reward: True
      draw_penalty: True
      activate_role_reward: False
      role_reward_param_file: null
      save_frequency: 500
      single_agent_mode: False
      min_height: 17000
      reward_win: 200
      reward_sparse: False
      reward_only_positive: False
      reward_death_value: 10
      reward_negative_scale: 0.5
      reward_scale: True
      reward_scale_rate: 20
      reward_defeat: -1
      numAMPObsSteps: 10

    player:
      render: False
      games_num: 200
      n_game_life: 1
      determenistic: False
      device: 'cpu'

  player:
    render: False
    games_num: 200
    n_game_life: 1
    determenistic: False
    device: 'cpu'
    num_agents: 2
    op_load_path: '/home/lzy/lzy/MARL/self-play/rl_games/runs/zhikong_20-21-23-03/nn/last_zhikong_ep_1060_rew_15.417396.pth'
