params:  
  algo:
    name: pfsp_con

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True
    normalization: layer_norm
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
          scale: 0.02
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True

    mlp:
      units: [512, 512, 128] #[1024, 1024, 512] #[128, 128, 64] # [512, 512, 128] #
      activation: elu # relu
      initializer:
        name: 'orthogonal_initializer'
      regularizer:
        name:  'None'

  config:
    name: zhikong_con
    env_name: zhikong_con
    player_pool_type: ''
    player_pool_length: 3
    op_load_path: False
    update_win_rate: 0.8
    games_to_check: 10
    score_to_win: 30
    max_epochs: 1000000
    bounds_loss_coef: 10
    max_update_steps: 5000
    reward_shaper:
        scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    save_win_threshold: 0.005
    grad_norm: 1.5
    entropy_coef: 0.0
    truncate_grads: True
    env_name: zhikong_con
    e_clip: 0.2
    clip_value: True
    clip_actions: True
    num_actors: 3
    horizon_length: 500
    minibatch_size: 500
    mini_epochs: 2
    critic_coef: 1
    lr_schedule:  linear
    kl_threshold: 0.05
    games_to_track: 10
    normalize_input: True
    normalize_value: True
    seq_length: 5
    save_frequency: 10
    save_best_after: 10
    # self_play: True

    env_config:
      name: zhikong_con
      ip: '127.0.1.1'
      worker_index: 888
      config_path: 'rl_games/configs/ma/ppo_zhikong_sp_con.yaml'
      excute_path: '/home/lzy/lzy/human-ai/Air/9-21/Linux/Mono/NoLinux/ZK.x86_64' #'/home/lzy/lzy/human-ai/Air/9-17/Linux/IL2CPP/Linux/ZK.x86_64'
      playmode: 0
      num_agents: 2
      red_agents_num: 1
      blue_agents_num: 1
      action_space_type: MultiDiscrete
      ctrl_mode: 0
      apply_agent_ids: True
      central_value: False
      episode_max_length: 500
      change_target: False
      render: False
      record_game_state: False
      dense_reward: True
      draw_penalty: True
      activate_role_reward: False
      role_reward_param_file: null
      save_frequency: 500
      single_agent_mode: False
      min_height: 17000
      reward_win: 200
      reward_sparse: False
      reward_only_positive: False
      reward_death_value: 10
      reward_negative_scale: 0.5
      reward_scale: True
      reward_scale_rate: 20
      reward_defeat: -1

    player:
      render: False
      games_num: 200
      n_game_life: 1
      determenistic: False
      device: 'cpu'

  player:
    render: False
    games_num: 200
    n_game_life: 1
    determenistic: True
    device: 'cpu'
    num_agents: 2
    op_load_path: '/home/lzy/lzy/MARL/self-play/models/9-24/last_zhikong_con_ep_2570_rew_12.714963.pth'